package hbi.core.demo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "my_test01")
public class Demo extends BaseDTO {

     public static final String FIELD_MY_ID = "myId";
     public static final String FIELD_MY_NAME = "myName";
     public static final String FIELD_MY_AGE = "myAge";
     public static final String FIELD_MY_BIRTHDAY = "myBirthday";


     @Id
     @GeneratedValue
     private String myId;

     @Length(max = 64)
     private String myName;

     private Long myAge;

     private Date myBirthday;


     public void setMyId(String myId){
         this.myId = myId;
     }

     public String getMyId(){
         return myId;
     }

     public void setMyName(String myName){
         this.myName = myName;
     }

     public String getMyName(){
         return myName;
     }

     public void setMyAge(Long myAge){
         this.myAge = myAge;
     }

     public Long getMyAge(){
         return myAge;
     }

     public void setMyBirthday(Date myBirthday){
         this.myBirthday = myBirthday;
     }

     public Date getMyBirthday(){
         return myBirthday;
     }

     }
